// teams.js - Fully functional version

const teamsData = [
  { name: "Ohio State", color: "#BA0C2F", conference: "Big Ten" },
  { name: "Texas", color: "#BF5700", conference: "SEC" },
  { name: "Notre Dame", color: "#0C2340", conference: "Independent" },
  { name: "Oregon", color: "#154733", conference: "Big Ten" },
  { name: "Georgia", color: "#BA0C2F", conference: "SEC" },
  { name: "Indiana", color: "#990000", conference: "Big Ten" },
  { name: "Miami", color: "#F47321", conference: "ACC" },
  { name: "Alabama", color: "#9E1B32", conference: "SEC" },
  { name: "LSU", color: "#461D7C", conference: "SEC" },
  { name: "Texas Tech", color: "#CC0000", conference: "Big 12" },
  { name: "Texas A&M", color: "#500000", conference: "SEC" },
  { name: "Oklahoma", color: "#841617", conference: "SEC" },
  { name: "USC", color: "#990000", conference: "Big Ten" },
  { name: "Ole Miss", color: "#CE1126", conference: "SEC" },
  { name: "Michigan", color: "#00274C", conference: "Big Ten" },
  { name: "Tennessee", color: "#FF8200", conference: "SEC" },
  { name: "Penn State", color: "#041E42", conference: "Big Ten" },
  { name: "Florida", color: "#0021A5", conference: "SEC" },
  { name: "Clemson", color: "#F56600", conference: "ACC" },
  { name: "BYU", color: "#002E5D", conference: "Big 12" },
  { name: "Missouri", color: "#F1B82D", conference: "SEC" },
  { name: "Auburn", color: "#0C2340", conference: "SEC" },
  { name: "South Carolina", color: "#73000A", conference: "SEC" },
  { name: "SMU", color: "#C8102E", conference: "ACC" },
  { name: "Iowa", color: "#FFCD00", conference: "Big Ten" },
  { name: "Washington", color: "#4B2E83", conference: "Big Ten" },
  { name: "Louisville", color: "#AD0000", conference: "ACC" },
  { name: "Florida State", color: "#782F40", conference: "ACC" },
  { name: "Vanderbilt", color: "#866D4B", conference: "SEC" },
  { name: "Nebraska", color: "#E41C38", conference: "Big Ten" },
  { name: "Utah", color: "#CC0000", conference: "Big 12" },
  { name: "Virginia", color: "#232D4B", conference: "ACC" },
  { name: "Virginia Tech", color: "#861F41", conference: "ACC" },
  { name: "Arizona", color: "#CC0033", conference: "Big 12" },
  { name: "Houston", color: "#C8102E", conference: "Big 12" },
  { name: "Pittsburgh", color: "#003594", conference: "ACC" },
  { name: "Baylor", color: "#154734", conference: "Big 12" },
  { name: "TCU", color: "#4D1979", conference: "Big 12" },
  { name: "Illinois", color: "#E84A27", conference: "Big Ten" },
  { name: "Kentucky", color: "#0033A0", conference: "SEC" },
  { name: "Kansas State", color: "#512888", conference: "Big 12" },
  { name: "North Carolina", color: "#7BAFD4", conference: "ACC" },
  { name: "Wisconsin", color: "#C5050C", conference: "Big Ten" },
  { name: "Arizona State", color: "#8C1D40", conference: "Big 12" },
  { name: "Colorado", color: "#CFB87C", conference: "Big 12" },
  { name: "Cincinnati", color: "#E00122", conference: "Big 12" },
  { name: "Arkansas", color: "#9D2235", conference: "SEC" },
  { name: "Georgia Tech", color: "#B3A369", conference: "ACC" },
  { name: "Mississippi State", color: "#5D1725", conference: "SEC" },
  { name: "Boise State", color: "#0033A0", conference: "Pac-12" },
  { name: "NC State", color: "#CC0000", conference: "ACC" },
  { name: "Duke", color: "#003087", conference: "ACC" },
  { name: "Wake Forest", color: "#9E7E38", conference: "ACC" },
  { name: "Oklahoma State", color: "#FF7300", conference: "Big 12" },
  { name: "Kansas", color: "#0051BA", conference: "Big 12" },
  { name: "Tulane", color: "#005837", conference: "American" },
  { name: "UCF", color: "#BA9B37", conference: "Big 12" },
  { name: "UNLV", color: "#B10202", conference: "Mountain West" },
  { name: "San Diego State", color: "#A6192E", conference: "Pac-12" },
  { name: "Northwestern", color: "#4E2A84", conference: "Big Ten" },
  { name: "Maryland", color: "#E03A3E", conference: "Big Ten" },
  { name: "California", color: "#003262", conference: "ACC" },
  { name: "Minnesota", color: "#7A0019", conference: "Big Ten" },
  { name: "UCLA", color: "#2774AE", conference: "Big Ten" },
  { name: "Michigan State", color: "#18453B", conference: "Big Ten" },
  { name: "West Virginia", color: "#002855", conference: "Big 12" },
  { name: "Rutgers", color: "#CC0033", conference: "Big Ten" },
  { name: "East Carolina", color: "#592A8A", conference: "American" },
  { name: "Navy", color: "#00205B", conference: "American" },
  { name: "Syracuse", color: "#F76900", conference: "ACC" },
  { name: "Purdue", color: "#CEB888", conference: "Big Ten" },
  { name: "Iowa State", color: "#C8102E", conference: "Big 12" },
  { name: "South Florida", color: "#006747", conference: "American" },
  { name: "Memphis", color: "#003087", conference: "American" },
  { name: "James Madison", color: "#450084", conference: "Sun Belt" },
  { name: "Hawai'i", color: "#024731", conference: "Mountain West" },
  { name: "Fresno State", color: "#DB0032", conference: "Pac-12" },
  { name: "Boston College", color: "#98002E", conference: "ACC" },
  { name: "Toledo", color: "#003E7E", conference: "MAC" },
  { name: "Stanford", color: "#8C1515", conference: "ACC" },
  { name: "New Mexico", color: "#BA0C2F", conference: "Mountain West" },
  { name: "Western Michigan", color: "#6C4023", conference: "MAC" },
  { name: "Washington State", color: "#981E32", conference: "Pac-12" },
  { name: "Texas State", color: "#501214", conference: "Pac-12" },
  { name: "Old Dominion", color: "#003057", conference: "Sun Belt" },
  { name: "Western Kentucky", color: "#C60C2F", conference: "Conference USA" },
  { name: "Southern Miss", color: "#FFAA00", conference: "Sun Belt" },
  { name: "UTSA", color: "#0C2340", conference: "American" },
  { name: "Army", color: "#D4AF37", conference: "American" },
  { name: "North Texas", color: "#00853E", conference: "American" },
  { name: "Delaware", color: "#00539F", conference: "Conference USA" },
  { name: "Utah State", color: "#0F2439", conference: "Pac-12" },
  { name: "Air Force", color: "#003087", conference: "Mountain West" },
  { name: "Miami (OH)", color: "#C41230", conference: "MAC" },
  { name: "Troy", color: "#8A2432", conference: "Sun Belt" },
  { name: "Liberty", color: "#002D62", conference: "Conference USA" },
  { name: "Ohio", color: "#00694E", conference: "MAC" },
  { name: "Oregon State", color: "#DC4405", conference: "Pac-12" },
  { name: "Louisiana", color: "#CE181E", conference: "Sun Belt" },
  { name: "North Dakota State", color: "#0A5640", conference: "Mountain West" },
  { name: "Jacksonville State", color: "#CC0000", conference: "Conference USA" },
  { name: "Temple", color: "#9D2235", conference: "American" },
  { name: "Georgia Southern", color: "#011E41", conference: "Sun Belt" },
  { name: "Marshall", color: "#00B140", conference: "Sun Belt" },
  { name: "Tulsa", color: "#002D72", conference: "American" },
  { name: "Kennesaw State", color: "#FDBB30", conference: "Conference USA" },
  { name: "Arkansas State", color: "#CC092F", conference: "Sun Belt" },
  { name: "Louisiana Tech", color: "#002F51", conference: "Sun Belt" },
  { name: "App State", color: "#FFC72C", conference: "Sun Belt" },
  { name: "Missouri State", color: "#5F0000", conference: "Conference USA" },
  { name: "Sacramento State", color: "#00573C", conference: "MAC" },
  { name: "South Alabama", color: "#00205B", conference: "Sun Belt" },
  { name: "Buffalo", color: "#005BBB", conference: "MAC" },
  { name: "UConn", color: "#000E2F", conference: "Independent" },
  { name: "Florida Atlantic", color: "#003366", conference: "American" },
  { name: "Nevada", color: "#003366", conference: "Mountain West" },
  { name: "Coastal Carolina", color: "#006F71", conference: "Sun Belt" },
  { name: "Colorado State", color: "#1E4D2B", conference: "Pac-12" },
  { name: "FIU", color: "#081E3F", conference: "Conference USA" },
  { name: "Central Michigan", color: "#6A0032", conference: "MAC" },
  { name: "Wyoming", color: "#492F24", conference: "Mountain West" },
  { name: "Rice", color: "#00205B", conference: "American" },
  { name: "Bowling Green", color: "#FE5000", conference: "MAC" },
  { name: "San José State", color: "#0055A2", conference: "Mountain West" },
  { name: "Northern Illinois", color: "#BA0C2F", conference: "Mountain West" },
  { name: "Charlotte", color: "#005035", conference: "American" },
  { name: "Georgia State", color: "#0039A6", conference: "Sun Belt" },
  { name: "UAB", color: "#1E6B52", conference: "American" },
  { name: "New Mexico State", color: "#8C0B13", conference: "Conference USA" },
  { name: "Middle Tennessee", color: "#0066A1", conference: "Conference USA" },
  { name: "Eastern Michigan", color: "#006633", conference: "MAC" },
  { name: "UTEP", color: "#FF8200", conference: "Mountain West" },
  { name: "Akron", color: "#041E42", conference: "MAC" },
  { name: "Ball State", color: "#BA0C2F", conference: "MAC" },
  { name: "Kent State", color: "#002664", conference: "MAC" },
  { name: "Sam Houston", color: "#F47920", conference: "Conference USA" },
  { name: "Massachusetts", color: "#881C1C", conference: "MAC" },
  { name: "UL Monroe", color: "#8A2432", conference: "Sun Belt" }
];

const teamsByFPI = teamsData.map(t => t.name);

const teamColors = {};
const teamConferences = {};

teamsData.forEach(t => {
  teamColors[t.name] = t.color;
  teamConferences[t.name] = t.conference;
});

const GROUP_OF_6 = new Set([
  "American",
  "Conference USA",
  "MAC",
  "Mountain West",
  "Pac-12",
  "Sun Belt"
]);
